"""modify relations from bidirectional to unidirectional

Revision ID: 55b19899db4a
Revises: e0fe2a6f7c3c
Create Date: 2024-01-23 16:03:18.566049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b19899db4a'
down_revision: Union[str, None] = 'e0fe2a6f7c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
