"""modify customer table

Revision ID: d6865f4375ad
Revises: 55b19899db4a
Create Date: 2024-01-24 13:00:16.346867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6865f4375ad'
down_revision: Union[str, None] = '55b19899db4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ET_CUSTOMER_A_customerID'), 'ET_CUSTOMER', ['A_customerID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ET_CUSTOMER_A_customerID'), table_name='ET_CUSTOMER')
    # ### end Alembic commands ###
