"""modify relation of branch and complaint

Revision ID: e0fe2a6f7c3c
Revises: 43d0691c0d62
Create Date: 2024-01-23 16:00:27.102437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fe2a6f7c3c'
down_revision: Union[str, None] = '43d0691c0d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
