"""create tables

Revision ID: e2bc17447000
Revises: 
Create Date: 2024-01-23 15:09:12.922716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bc17447000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ET_BRANCH',
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_country', sa.String(length=10), nullable=True),
    sa.Column('A_state', sa.String(length=50), nullable=True),
    sa.Column('A_city', sa.String(length=50), nullable=True),
    sa.Column('A_street', sa.String(length=50), nullable=True),
    sa.Column('A_phoneNo', sa.String(length=11), nullable=True),
    sa.Column('A_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('A_openingTime', sa.Time(), nullable=True),
    sa.Column('A_closingTime', sa.Time(), nullable=True),
    sa.Column('A_startDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('A_branchNo')
    )
    op.create_table('ET_CUSTOMER',
    sa.Column('A_customerID', sa.String(length=20), nullable=False),
    sa.Column('A_firstName', sa.String(length=50), nullable=True),
    sa.Column('A_lastName', sa.String(length=50), nullable=True),
    sa.Column('A_age', sa.Integer(), nullable=True),
    sa.Column('A_gender', sa.String(length=3), nullable=True),
    sa.Column('A_phoneNumber', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('A_customerID')
    )
    op.create_table('ET_BARISTA',
    sa.Column('A_employeeNo', sa.String(length=16), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_firstName', sa.String(length=100), nullable=True),
    sa.Column('A_lastName', sa.String(length=50), nullable=True),
    sa.Column('A_age', sa.Integer(), nullable=True),
    sa.Column('A_gender', sa.String(length=3), nullable=True),
    sa.Column('A_salary', sa.Integer(), nullable=True),
    sa.Column('A_phoneNo', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_employeeNo')
    )
    op.create_table('ET_CASHIER',
    sa.Column('A_employeeNo', sa.String(length=16), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_firstName', sa.String(length=50), nullable=True),
    sa.Column('A_lastName', sa.String(length=50), nullable=True),
    sa.Column('A_age', sa.Integer(), nullable=True),
    sa.Column('A_gender', sa.String(length=3), nullable=True),
    sa.Column('A_salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('A_phoneNo', sa.String(length=11), nullable=True),
    sa.Column('A_password', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_employeeNo')
    )
    op.create_table('ET_EQUIPMENT',
    sa.Column('A_equipmentNo', sa.String(length=15), nullable=False),
    sa.Column('A_equipmentName', sa.String(length=100), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_equipDate', sa.Date(), nullable=True),
    sa.Column('A_equipmentValue', sa.Integer(), nullable=True),
    sa.Column('A_equipmentStatus', sa.String(length=100), nullable=True),
    sa.Column('A_equipmentColor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_equipmentNo')
    )
    op.create_table('ET_MANAGER',
    sa.Column('A_employeeNo', sa.String(length=16), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_firstName', sa.String(length=100), nullable=True),
    sa.Column('A_lastName', sa.String(length=50), nullable=True),
    sa.Column('A_age', sa.Integer(), nullable=True),
    sa.Column('A_gender', sa.String(length=3), nullable=True),
    sa.Column('A_salary', sa.Integer(), nullable=True),
    sa.Column('A_phoneNo', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_employeeNo')
    )
    op.create_table('ET_MENU',
    sa.Column('A_itemID', sa.String(length=6), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_itemName', sa.String(length=50), nullable=True),
    sa.Column('A_price', sa.Integer(), nullable=True),
    sa.Column('A_recipe', sa.String(length=300), nullable=True),
    sa.Column('A_averageScore', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_itemID')
    )
    op.create_table('ET_MONTHLYEXPENSE',
    sa.Column('A_expenseID', sa.Integer(), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_year', sa.String(length=4), nullable=True),
    sa.Column('A_month', sa.String(length=20), nullable=True),
    sa.Column('A_rent', sa.Integer(), nullable=True),
    sa.Column('A_totalSalary', sa.Integer(), nullable=True),
    sa.Column('A_bill', sa.Integer(), nullable=True),
    sa.Column('A_ingredient', sa.Integer(), nullable=True),
    sa.Column('A_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_expenseID')
    )
    op.create_table('ET_PERCHASINGOFFICER',
    sa.Column('A_employeeNo', sa.String(length=16), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_firstName', sa.String(length=100), nullable=True),
    sa.Column('A_lastName', sa.String(length=50), nullable=True),
    sa.Column('A_age', sa.Integer(), nullable=True),
    sa.Column('A_gender', sa.String(length=3), nullable=True),
    sa.Column('A_salary', sa.Integer(), nullable=True),
    sa.Column('A_phoneNo', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.PrimaryKeyConstraint('A_employeeNo')
    )
    op.create_table('RT_COMPLAINT',
    sa.Column('A_complaintID', sa.Integer(), nullable=False),
    sa.Column('A_branchNo', sa.String(length=6), nullable=False),
    sa.Column('A_customerID', sa.String(length=20), nullable=False),
    sa.Column('A_content', sa.Text(), nullable=False),
    sa.Column('A_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['A_branchNo'], ['ET_BRANCH.A_branchNo'], ),
    sa.ForeignKeyConstraint(['A_customerID'], ['ET_CUSTOMER.A_customerID'], ),
    sa.PrimaryKeyConstraint('A_complaintID')
    )
    op.create_table('RT_ORDER',
    sa.Column('A_orderID', sa.Integer(), nullable=False),
    sa.Column('A_employeeNo', sa.String(length=16), nullable=False),
    sa.Column('A_customerID', sa.String(length=20), nullable=False),
    sa.Column('A_totalPrice', sa.DECIMAL(precision=30, scale=2), nullable=False),
    sa.Column('A_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['A_customerID'], ['ET_CUSTOMER.A_customerID'], ),
    sa.ForeignKeyConstraint(['A_employeeNo'], ['ET_CASHIER.A_employeeNo'], ),
    sa.PrimaryKeyConstraint('A_orderID')
    )
    op.create_table('ET_ORDEREDITEM',
    sa.Column('A_orderID', sa.Integer(), nullable=False),
    sa.Column('A_itemID', sa.String(length=6), nullable=False),
    sa.Column('A_itemScore', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['A_itemID'], ['ET_MENU.A_itemID'], ),
    sa.ForeignKeyConstraint(['A_orderID'], ['RT_ORDER.A_orderID'], ),
    sa.PrimaryKeyConstraint('A_orderID', 'A_itemID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ET_ORDEREDITEM')
    op.drop_table('RT_ORDER')
    op.drop_table('RT_COMPLAINT')
    op.drop_table('ET_PERCHASINGOFFICER')
    op.drop_table('ET_MONTHLYEXPENSE')
    op.drop_table('ET_MENU')
    op.drop_table('ET_MANAGER')
    op.drop_table('ET_EQUIPMENT')
    op.drop_table('ET_CASHIER')
    op.drop_table('ET_BARISTA')
    op.drop_table('ET_CUSTOMER')
    op.drop_table('ET_BRANCH')
    # ### end Alembic commands ###
